### ISSUE TITLE
Adding More Examples

### ISSUE THREAD

**Issue by Siddhant-K-code** [gaurav-gogia/mutant#1]
Adding More Examples in Separate Repo with most Common programs we use to learn other languages in a separate Repo. which will contain Examples Only. And, We should make Organisation with a mutant that contains Repos. of Mutant Docs, Mutant, Mutant-Examples

**Comment by gaurav-gogia** [comment]
@Siddhant-K-code thanks for raising this issue. I'll try to answer point by point.

1. We could use a common repo for all example programs in future. But for now all examples are being handled via [official mutant website](https://mudocs.netlify.app) only

2. Migrating to an organisation is not on roadmap at the moment. It's sort of a big decision, depending on maturity and adoption of this program, migration will be planned in future. 

I hope this helps :)
